### ISSUE TITLE
Sample which uses onSaveInstanceState / onCreate(savedInstanceState) 

### ISSUE THREAD

**Issue by Zhuinden** [mboudraa/flow#2]

**Comment by mboudraa** [comment]
Hi are you asking how to save the state of the flow using onSaveInstanceState? So we can retrieve it in onCreate?

**Comment by Zhuinden** [comment]
I'm actually just making a note here that this is something that'd be nice for this lib and *might* look into doing if doesn't exist, I attended the talk today and that was what I was missing :D nice lib btw
